/**
 * This class is generated by jOOQ
 */
package com.hellokoding.jooq.model;


import com.hellokoding.jooq.model.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.hellokoding.jooq.model.tables.Author.AUTHOR;
}
